### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'dtype

### ISSUE THREAD

**Issue by yukiarimo** [daswer123/rvc-python#13]
Log:
```
(rvc) yuki@yuki ~ % python -m rvc_python -i /Users/yuki/Downloads/yukiarimottsnew/dataset/wavs/ynew100p_00000001.wav -mp /Users/yuki/Library/Application\ Support/Replay/com.replay.Replay/models/yuna-ai-v2/yuna-ai-v2.pth
2024-07-02 02:20:58 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2024-07-02 02:20:58 | INFO | rvc_python.configs.config | No supported Nvidia GPU found, using MPS
overwrite preprocess and configs.json
2024-07-02 02:20:58 | INFO | rvc_python.configs.config | Use mps instead
is_half:False, device:mps
2024-07-02 02:20:58 | INFO | rvc_python.modules.vc.modules | Loading: /Users/yuki/Library/Application Support/Replay/com.replay.Replay/models/yuna-ai-v2/yuna-ai-v2.pth
/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/rvc_python/modules/vc/modules.py:103: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.cpt = torch.load(sid, map_location="cpu")
/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
gin_channels: 256 self.spk_embed_dim: 109
/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/fairseq/checkpoint_utils.py:315: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(f, map_location=torch.device("cpu"))
2024-07-02 02:20:58 | INFO | fairseq.tasks.hubert_pretraining | current directory is /Users/yuki
2024-07-02 02:20:58 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2024-07-02 02:20:58 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/torch/nn/functional.py:5092: UserWarning: MPS: The constant padding of more than 3 dimensions is not currently supported natively. It uses View Ops default implementation to run. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Pad.mm:472.)
  return torch._C._nn.pad(input, pad, mode, value)
2024-07-02 02:21:02 | WARNING | rvc_python.modules.vc.modules | Traceback (most recent call last):
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/rvc_python/modules/vc/modules.py", line 184, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/rvc_python/modules/vc/pipeline.py", line 415, in pipeline
    self.vc(
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/rvc_python/modules/vc/pipeline.py", line 274, in vc
    audio1 = (net_g.infer(*arg)[0][0, 0]).data.cpu().float().numpy()
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/rvc_python/lib/infer_pack/models.py", line 762, in infer
    o = self.dec(z * x_mask, nsff0, g=g)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1714, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1725, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/rvc_python/lib/infer_pack/models.py", line 506, in forward
    x_source = self.noise_convs[i](har_source)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1714, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1725, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 373, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 368, in _conv_forward
    return F.conv1d(
NotImplementedError: Output channels > 65536 not supported at the MPS device. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

Traceback (most recent call last):
  File "/opt/anaconda3/envs/rvc/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/rvc/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/rvc_python/__main__.py", line 31, in <module>
    inferred_path = infer_file(
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/rvc_python/infer.py", line 49, in infer_file
    wavfile.write(opt_path, vc.tgt_sr, wav_opt)
  File "/opt/anaconda3/envs/rvc/lib/python3.10/site-packages/scipy/io/wavfile.py", line 798, in write
    dkind = data.dtype.kind
AttributeError: 'tuple' object has no attribute 'dtype'
(rvc) yuki@yuki ~ % 
```

**Comment by yukiarimo** [comment]
Fixed using Python 3.9. Anyway to use it with 3.10?

**Comment by wirytiox** [comment]
i tried 3.10 and it doesn't work. i will try 3.9 now.

**Comment by wirytiox** [comment]
i am using 3.9.0 and i still have the issue:
```2024-09-12 11:10:17.412 | INFO     | rvc_python.api:rvc_convert:33 - Received request to convert audio
2024-09-12 11:10:17 | WARNING | rvc_python.modules.vc.modules | Traceback (most recent call last):
  File "C:\Users\juanj\Desktop\blyat\rvc\venv\lib\site-packages\rvc_python\lib\audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "C:\Users\juanj\Desktop\blyat\rvc\venv\lib\site-packages\rvc_python\lib\audio.py", line 41, in audio2
    ostream = out.add_stream(format, channels=1)
  File "av\\container\\output.pyx", line 132, in av.container.output.OutputContainer.add_stream
  File "av\\stream.pyx", line 111, in av.stream.Stream.__setattr__
AttributeError: attribute 'channels' of 'av.audio.codeccontext.AudioCodecContext' objects is not writable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\juanj\Desktop\blyat\rvc\venv\lib\site-packages\rvc_python\modules\vc\modules.py", line 161, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\juanj\Desktop\blyat\rvc\venv\lib\site-packages\rvc_python\lib\audio.py", line 67, in load_audio
    audio = file[1] / 32768.0
TypeError: unsupported operand type(s) for /: 'str' and 'float'

2024-09-12 11:10:17.420 | ERROR    | rvc_python.api:rvc_convert:44 - 'tuple' object has no attribute 'dtype'
INFO:     127.0.0.1:53642 - "POST /convert HTTP/1.1" 500 Internal Server Err

**Comment by MoeMonsuta** [comment]
> i am using 3.9.0 and i still have an issue. a different one though.:
> 
> ```
> 2024-09-12 11:10:17 | WARNING | rvc_python.modules.vc.modules | Traceback (most recent call last):
>   File "C:\Users\juanj\Desktop\blyat\rvc\venv\lib\site-packages\rvc_python\lib\audio.py", line 63, in load_audio
>     audio2(f, out, "f32le", sr)
>   File "C:\Users\juanj\Desktop\blyat\rvc\venv\lib\site-packages\rvc_python\lib\audio.py", line 41, in audio2
>     ostream = out.add_stream(format, channels=1)
>   File "av\\container\\output.pyx", line 132, in av.container.output.OutputContainer.add_stream
>   File "av\\stream.pyx", line 111, in av.stream.Stream.__setattr__
> AttributeError: attribute 'channels' of 'av.audio.codeccontext.AudioCodecContext' objects is not writable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\juanj\Desktop\blyat\rvc\venv\lib\site-packages\rvc_python\modules\vc\modules.py", line 161, in vc_single
>     audio = load_audio(input_audio_path, 16000)
>   File "C:\Users\juanj\Desktop\blyat\rvc\venv\lib\site-packages\rvc_python\lib\audio.py", line 67, in load_audio
>     audio = file[1] / 32768.0
> TypeError: unsupported operand type(s) for /: 'str' and 'float'
> 
> 2024-09-12 11:10:17.420 | ERROR    | rvc_python.api:rvc_convert:44 - 'tuple' object has no attribute 'dtype'
> INFO:     127.0.0.1:53642 - "POST /convert HTTP/1.1" 500 Internal Server Err
> ```

I am having this same problem. You seem to be the only active person here and I'm lost on how to fix any of this.

**Comment by Cohee1207** [comment]
This should've been fixed in [0.1.4](https://github.com/daswer123/rvc-python/releases/tag/0.1.4)

Try upgrading the package if you've installed from pip:
`pip install --upgrade rvc-python`

**Comment by sachin-seisei** [comment]
@daswer123  @Cohee1207 i Tried upgrading as mentioned still i am getting the error as per the issue title can any one of you help me in this regard?? when i upload a wav file in the /convert_file end point this error is popping up!!
INFO:     127.0.0.1:34404 - "POST /models/rvc1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:34412 - "GET /models HTTP/1.1" 200 OK
INFO:     127.0.0.1:36334 - "POST /set_device HTTP/1.1" 200 OK
INFO:     127.0.0.1:36334 - "POST /set_device HTTP/1.1" 200 OK
2024-10-28 08:22:06.878 | INFO     | rvc_python.api:rvc_convert_file:76 - Received file to convert
2024-10-28 08:22:07 | INFO | fairseq.tasks.hubert_pretraining | current directory is /home/jovyan/RVC/rvc-python/rvc_python
2024-10-28 08:22:07 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2024-10-28 08:22:07 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
2024-10-28 08:22:08 | INFO | rvc_python.modules.vc.pipeline | Loading rmvpe model - base_models/rmvpe.pth
2024-10-28 08:22:09 | WARNING | rvc_python.modules.vc.modules | Traceback (most recent call last):
  File "/home/jovyan/RVC/rvc-python/rvc_python/modules/vc/modules.py", line 184, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "/home/jovyan/RVC/rvc-python/rvc_python/modules/vc/pipeline.py", line 359, in pipeline
    pitch, pitchf = self.get_f0(
  File "/home/jovyan/RVC/rvc-python/rvc_python/modules/vc/pipeline.py", line 157, in get_f0
    f0 = self.model_rmvpe.infer_from_audio(x, thred=0.03)
  File "/home/jovyan/RVC/rvc-python/rvc_python/lib/rmvpe.py", line 605, in infer_from_audio
    hidden = self.mel2hidden(mel)
  File "/home/jovyan/RVC/rvc-python/rvc_python/lib/rmvpe.py", line 584, in mel2hidden
    hidden = self.model(mel)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/RVC/rvc-python/rvc_python/lib/rmvpe.py", line 409, in forward
    x = self.cnn(self.unet(mel)).transpose(1, 2).flatten(-2)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/RVC/rvc-python/rvc_python/lib/rmvpe.py", line 367, in forward
    x, concat_tensors = self.encoder(x)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/RVC/rvc-python/rvc_python/lib/rmvpe.py", line 244, in forward
    x = self.bn(x)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/jovyan/.conda/envs/rvc/lib/python3.10/site-packages/torch/nn/functional.py", line 2478, in batch_norm
    return torch.batch_norm(
RuntimeError: "batch_norm" not implemented for 'Half'

2024-10-28 08:22:09.595 | ERROR    | rvc_python.api:rvc_convert_file:93 - 'tuple' object has no attribute 'dtype'
INFO:     127.0.0.1:36346 - "POST /convert_file HTTP/1.1" 500 Internal Server Error
